spring:
  zipkin:
    base-url: base-url: http://${ZIPKIN_URL:localhost}:9411
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Marcelo Barbosa
  mail: marogoba@gmail.com
  cel: 6161616161
server:
  port: ${PORT:9999}
message: Mensagem generica

queue:
  movie-service: queue-movie-service


## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
        
