server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: LogFilter
      routes:
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-api/**
        - id: movieRoute
          uri: http://localhost:8091/movie-api
          predicates:
            - Path=/movie-api/**
